export const FETCH_NODES = 'FETCH_NODES';
export const CREATE_NODE = 'CREATE_NODE';
export const FETCH_NODE = 'FETCH_NODE';
export const DELETE_NODE = 'DELETE_NODE';

export const MQTT_CONNECT = 'MQTT_START_TRYING_TO_CONNECT';
export const MQTT_CONNECTED = 'MQTT_CONNECTED';
export const MQTT_DISCONNECT = 'MQTT_DISCONNECT';
export const MQTT_DISCONNECTED = 'MQTT_DISCONNECTED';