export const SET_REDIRECT_ON_AUTH = 'SET_REDIRECT_ON_AUTH';

export const AUTHED_USER = 'AUTHED_USER';
export const AUTHFAILED_USER = 'AUTHFAILED_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
