export const SCHEDULE_FETCHED = 'SCHEDULE_FETCHED';
export const SCHEDULES_INVALID = 'SCHEDULES_INVALID';
export const SCHEDULES_FETCHING = 'SCHEDULES_FETCHING';
export const SCHEDULES_FETCH_FAILED = 'SCHEDULES_FETCH_FAILED';