export const SCHEDULE_FETCHED = 'SCHEDULE_FETCHED';
export const SCHEDULES_INVALID = 'SCHEDULES_INVALID';
export const SCHEDULES_FETCHING = 'SCHEDULES_FETCHING';
export const SCHEDULES_FETCH_FAILED = 'SCHEDULES_FETCH_FAILED';



export const CYCLE_CREATEING = 'CYCLE_CREATEING';
export const CYCLE_CREATED = 'CYCLE_CREATEED';
export const CYCLE_CREATE_FAILED = 'CYCLE_CREATE_FAILED';
export const CYCLE_FETCHED = 'CYCLE_FETCHED';
export const CYCLE_FETCHING = 'CYCLES_FETCHING';
export const CYCLE_FETCH_FAILED = 'CYCLES_FETCH_FAILED';